version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: angular
    versions:
    - ">= 0"
  - dependency-name: jquery
    versions:
    - ">= 0"
  - dependency-name: mime-db
    versions:
    - "^1.35.0"
  - dependency-name: "@types/node"
    versions:
    - "^10.12.18"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
